USE ADVENTURE_WORK;

SELECT * FROM CUSTOMER_DATA;
SELECT * FROM PRODUCT_DATA;
SELECT * FROM SALE_DATA;
SELECT * FROM LOCATION;



SELECT CAST(SALE.OrderDate AS DATE) AS ORDER_DATE,CAST(SALE.ShipDate AS DATE) AS SHIPED_DATE,
SALE.SalesOrderNumber,
DATEDIFF(year,CUS.BirthDate,getdate())  AS CUSTOME_BIRTHDAY ,
CONCAT(CUS.FirstName,' ',CUS.LastName) AS NAME_CUSTMOER,
SALE.OrderQuantity,SALE.UnitPrice,SALE.TotalProductCost,SalesAmount,SALE.TaxAmt 
, CUS.MaritalStatus,CUS.Gender,CUS.Education,
CUS.Occupation,CAST(CUS.DateFirstPurchase AS DATE) AS DATE_FIRST_PURCHASE, PRO.ProductName,
LOC.Country as country
INTO MASTERTABLE
FROM SALE_DATA AS SALE
INNER JOIN CUSTOMER_DATA AS CUS
ON SALE.CustomerKey = CUS.CustomerKey
INNER JOIN PRODUCT_DATA AS PRO
ON SALE.ProductKey=PRO.ProductKey
INNER JOIN LOCATION AS LOC 
ON SALE.SalesTerritoryKey = LOC.SalesTerritoryKey


